### ISSUE TITLE
Could not find function "mgnify_get_downloads"

### ISSUE THREAD

**Issue by stitam** [beadyallen/MGnifyR#2]
Hi, thanks @beadyallen for developing this package! I've recently started using it and found a small issue. The man file for `mgnify_download()` contains the following line within the examples: `downloads <- mgnify_get_downloads(mg, accession_vect, "analyses")`. However, when I try to run it it gives the following error: 

```
Error in mgnify_get_downloads(mg, accession_vect, "analyses") : 
  could not find function "mgnify_get_downloads"
```

I suspect that the name of the function has been updated to `mgnify_get_download_urls()` which works flawlessly.

**Comment by beadyallen** [comment]
Yep - you're right. That was a typo. Thanks
